export enum ControlTypeEnum {
    Checkbox = 'Checkbox',
    DatePicker = 'DatePicker',
    DateTimePicker = 'DateTimePicker',
    Dropdown = 'Dropdown',
    Email = 'Email',
    InputSwitch = 'InputSwitch',
    Number = 'Number',
    MaskedTextbox = 'MaskedTextbox',
    MultiSelect = 'MultiSelect',
    Password = 'Password',
    PhoneNumber = 'PhoneNumber',
    RadioButton = 'RadioButton',
    SelectButton = 'SelectButton',
    TextArea = 'TextArea',
    Textbox = 'Textbox',
    TimePicker = 'TimePicker',
  }
