export type FieldRuleActionType =
  | 'show'
  | 'hide'
  | 'require'
  | 'optional'
  | 'disable'
  | 'enable'
  | 'readonly'
  | 'editable'
  | 'setMin'
  | 'setMax'
  | 'setMinDate'
  | 'setMaxDate'
  | 'setMinLength'
  | 'setMaxLength'
  | 'setPattern'
  | 'setOptions'
  | 'setValue';
